project_id = "lhamshhjmmruybdcfivr"

[functions.ai-chat-assistant]
verify_jwt = false

[functions.medicine-lookup]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = false

[functions.speech-to-text]
verify_jwt = false